apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr1
  namespace: sonarr1
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: sonarr1
  data:
  - secretKey: SONARR__API_KEY
    remoteRef:
      key: SONARR__API_KEY
