apiVersion: v1
kind: ConfigMap
metadata:
  name: vrising
data:
  TZ: Europe/Vilnius
  VR_NAME: origin
  VR_PASSWORD: origin.lt
  VR_DESCRIPTION: "Serverio discord invite linkas www.origin.lt"
  VR_MAX_USERS: "8"
  VR_MAX_ADMINS: "2"
  VR_FPS: "120"
  VR_LOWER_FPS_WHEN_EMPTY: "true"
  VR_SECURE: "true"
  VR_LIST_ON_STEAM: "true"
  VR_HIDEIPADDRESS: "true"
