apiVersion: v1
kind: Service
metadata:
  name: vrising
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.224
spec:
  ports:
  - name: app
    port: 9876
    targetPort: 9876
    protocol: UDP
  - name: query
    port: 9877
    targetPort: 9877
    protocol: UDP
  selector:
    app: vrising
  type: LoadBalancer
