apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin
  data:
  - secretKey: admin-password
    remoteRef:
      key: GRAFANA_ADMIN_PASSWORD
