apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
namespace: victoriametrics

#patches:
#- path: ./patches/deployment-operator.yaml
#  target:
#    version: v1
#    kind: Deployment
#    name: victoria-metrics-k8s-stack-victoria-metrics-operator

helmGlobals:
  chartHome: charts
helmCharts:
- name: victoria-metrics-k8s-stack
  version: 0.25.17
  repo: https://victoriametrics.github.io/helm-charts
  releaseName: victoria-metrics-k8s-stack
  includeCRDs: true
  namespace: victoriametrics
  valuesFile: values.yaml
