apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmGlobals:
  chartHome: charts
helmCharts:
- name: victoria-metrics-k8s-stack
  version: 0.25.3
  repo: https://victoriametrics.github.io/helm-charts
  releaseName: victoria-metrics-k8s-stack
  namespace: victoriametrics
  valuesFile: values.yaml
