apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml
- ./configmap.yaml
- ./pvc.yaml

images:
- name: ghcr.io/plexguide/huntarr
  newTag: "9.4.3"
