apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
