apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: opentelemetry-collector
  version: 0.147.1
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  releaseName: otel-collector
  namespace: otel-collector
  valuesFile: values.yaml
