mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  processors:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15
    batch:
      send_batch_size: 10000
      timeout: 10s
    filter/drop_probes:
      error_mode: ignore
      traces:
        span:
        - 'IsMatch(attributes["http.target"], ".*/livez$")'
        - 'IsMatch(attributes["http.target"], ".*/readyz$")'
        - 'IsMatch(attributes["http.target"], ".*/healthz$")'
        - 'IsMatch(attributes["url.path"], ".*/livez$")'
        - 'IsMatch(attributes["url.path"], ".*/readyz$")'
        - 'IsMatch(attributes["url.path"], ".*/healthz$")'
      logs:
        log_record:
        - 'IsMatch(attributes["http.target"], ".*/livez$")'
        - 'IsMatch(attributes["http.target"], ".*/readyz$")'
        - 'IsMatch(attributes["http.target"], ".*/healthz$")'
        - 'IsMatch(attributes["url.path"], ".*/livez$")'
        - 'IsMatch(attributes["url.path"], ".*/readyz$")'
        - 'IsMatch(attributes["url.path"], ".*/healthz$")'

  exporters:
    otlphttp/tempo:
      endpoint: http://tempo.tempo.svc:4318
    loki:
      endpoint: http://loki.loki.svc:3100/loki/api/v1/push
    prometheusremotewrite/victoriametrics:
      endpoint: http://vmsingle-victoria-metrics-k8s-stack.victoriametrics.svc:8429/api/v1/write

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [memory_limiter, filter/drop_probes, batch]
        exporters: [otlphttp/tempo]
      metrics:
        receivers: [otlp]
        processors: [memory_limiter, filter/drop_probes, batch]
        exporters: [prometheusremotewrite/victoriametrics]
      logs:
        receivers: [otlp]
        processors: [memory_limiter, filter/drop_probes, batch]
        exporters: [loki]
