apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  template:
    spec:
      volumes:
        - name: homepage-config
          $patch: replace
          secret:
            secretName: homepage