apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  namespace: radarr
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    nginx.ingress.kubernetes.io/auth-url: "https://login.sync.lt:8443/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.sync.lt:8443/oauth2/start?rd=$scheme://$best_http_host$escaped_request_uri"
spec:
  # tls:
  # - hosts:
  #   - radarr.sync.lt
  #   secretName: radarr-letsencrypt
  rules:
  - host: radarr.sync.lt
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              name: app
