apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blocky
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: blocky
  data:
  - secretKey: WEBPASSWORD
    remoteRef:
      key: blocky_WEBPASSWORD
