apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blocky-querylogs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
