apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-bot
data:
  RENOVATE_PLATFORM: github
  RENOVATE_AUTODISCOVER: 'false'
  RENOVATE_REPOSITORIES: '["AurimasNav/k8s-at-home"]'
  RENOVATE_BASE_DIR: /tmp/renovate/
  RENOVATE_CONFIG_FILE: /opt/renovate/config.js
  LOG_LEVEL: debug 
  #RENOVATE_DRY_RUN: full
  RENOVATE_GIT_AUTHOR: "Renovate Bot <fake@mail.com>"
  RENOVATE_PR_HOURLY_LIMIT: '20'
  RENOVATE_SEPARATE_MAJOR_MINOR: 'false'
  RENOVATE_EXPOSE_ALL_ENV: 'true'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.js: |-
    module.exports = {
      "kubernetes": {
        "fileMatch": ["gitops\\/.*\\/.*\\.ya?ml$"],
        "ignorePaths": ["**/gitops/**/kustomization.yaml"]
      },
      "regexManagers": [
        {
          "fileMatch": ".*kustomization\\.yaml",
          "matchStrings": ["https:\\/\\/github\\.com\\/(?<depName>.*\\/.*?)\\/releases\\/download\\/(?<currentValue>.*?)\\/", "https:\\/\\/raw\\.githubusercontent\\.com\\/(?<depName>[^\\/]*\\/[^\\/]*)\\/(?<currentValue>.*?)\\/"],
          "datasourceTemplate": "github-releases",
        },
        {
          "fileMatch": ".*kustomization\\.yaml",
          "matchStrings": ["https:\\/\\/github\\.com\\/(?<depName>.*\\/.*?)\\/releases\\/download\\/(?<currentValue>.*?)\\/", "https:\\/\\/raw\\.githubusercontent\\.com\\/(?<depName>[^\\/]*\\/[^\\/]*)\\/(?<currentValue>.*?)\\/"],
          "datasourceTemplate": "github-tags",
        },
        {
          "fileMatch": ".*\\/kustomization\\.yaml",
          "matchStrings": ["https:\/\/github\\.com\/(?<depName>.*\/.*?)\/releases\/download\/(?<currentValue>.*?)\/", "https:\/\/raw\\.githubusercontent\\.com\/(?<depName>[^\/]*\/[^\/]*)\/(?<currentValue>.*?)\/"],
          "datasourceTemplate": "github-releases",
        },
        {
          "fileMatch": ".*\\/kustomization\\.yaml",
          "matchStrings": ["https:\/\/github\\.com\/(?<depName>.*\/.*?)\/releases\/download\/(?<currentValue>.*?)\/", "https:\/\/raw\\.githubusercontent\\.com\/(?<depName>[^\/]*\/[^\/]*)\/(?<currentValue>.*?)\/"],
          "datasourceTemplate": "github-tags",
        }
      ]
    }
