apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate-bot
spec:
  schedule: '@daily'
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 72000
      template:
        spec:
          containers:
            - image: renovate/renovate:37.33.6
              name: renovate-bot
              envFrom:
              - secretRef:
                  name: renovate-bot
              - configMapRef:
                  name: renovate-bot
              volumeMounts:
              - name: config-vol
                mountPath: /opt/renovate/
              - name: work-volume
                mountPath: /tmp/renovate/
          restartPolicy: Never
          volumes:
          - name: work-volume
            emptyDir: {}
          - name: config-vol
            configMap:
              name: renovate-config