apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
namespace: jenkins

helmGlobals:
  chartHome: charts
helmCharts:
- name: jenkins
  version: 5.7.8
  repo: https://charts.jenkins.io
  releaseName: jenkins
  includeCRDs: true
  namespace: jenkins
  valuesFile: values.yaml
