apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ombi
  namespace: ombi
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "https://login.sync.lt/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://login.sync.lt/oauth2/start?rd=$scheme://$best_http_host$escaped_request_uri"
spec:
  tls:
  - hosts:
    - sync.lt
    - ombi.sync.lt
    secretName: ombi-letsencrypt
  rules:
  - host: sync.lt
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ombi
            port:
              name: app
  - host: ombi.sync.lt
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ombi
            port:
              name: app
              
