apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: pihole
  data:
  - secretKey: WEBPASSWORD
    remoteRef:
      key: PIHOLE_WEBPASSWORD
