apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole
  namespace: pihole
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.53
spec:
  ports:
  - name: webgui
    port: 80
    protocol: TCP  
    targetPort: 80
    appProtocol: http
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
    appProtocol: domain
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
    appProtocol: domain
  - name: dhcp
    port: 67
    protocol: UDP
    targetPort: 67
    appProtocol: bootps
  selector:
    app: pihole
  type: LoadBalancer
