apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: postgresql
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: postgresql
  dataFrom:
  - extract:
      key: POSTGRESQL
