apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
  namespace: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        envFrom:
        - configMapRef:
            name: unbound
        image: mvance/unbound:latest
        imagePullPolicy: Always
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
