apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unbound
  name: unbound
  namespace: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: mvance/unbound:latest
        imagePullPolicy: Always
        ports:
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        volumeMounts:
        - name: root-hints
          mountPath: /opt/unbound/etc/unbound/root.hints
          subPath: root.hints
        - name: unbound-config
          mountPath: /opt/unbound/etc/unbound/unbound.conf
          subPath: unbound.conf
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
      volumes:
      - name: root-hints
        configMap:
          name: root-hints
      - name: unbound-config
        configMap:
          name: unbound
