apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unbound
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: unbound
  data:
  - secretKey: WEBPASSWORD
    remoteRef:
      key: unbound_WEBPASSWORD
