apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml
- ./configmap.yaml
#- ./pvc.yaml

configMapGenerator:
- name: root-hints
  files:
  - root.hints=https://www.internic.net/domain/named.root
