apiVersion: v1
kind: Service
metadata:
  labels:
    app: unbound
  name: unbound
  namespace: unbound
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.154
spec:
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
    appProtocol: domain
  - name: dns-udp
    port: 53
    protocol: UDP
    targetPort: 53
    appProtocol: domain
  selector:
    app: unbound
  type: LoadBalancer
