apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-auth-api
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-token-auth-api
            key: dopplerToken
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: doppler-auth-api
    kind: ClusterSecretStore
  target:
    name: example-sync
  data:
  - secretKey: LETSENCRYPT_EMAIL
    remoteRef:
      key: LETSENCRYPT_EMAIL
