apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: charts
helmCharts:
- name: vault
  version: latest
  repo: https://helm.releases.hashicorp.com
  releaseName: vault
  namespace: vault
  valuesFile: values.yaml
