apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared
  data:
  - secretKey: credentials.json
    remoteRef:
      key: CLOUDFLARE_CREDENTIALS_JSON
