apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: mysql
  dataFrom:
  - extract:
      key: MYSQL
