apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: homepage
  data:
  - secretKey: bookmarks.yaml
    remoteRef:
      key: HOMEPAGE_BOOKMARKS
  - secretKey: docker.yaml
    remoteRef:
      key: HOMEPAGE_DOCKER
  - secretKey: kubernetes.yaml
    remoteRef:
      key: HOMEPAGE_KUBERNETES
  - secretKey: services.yaml
    remoteRef:
      key: HOMEPAGE_SERVICES
  - secretKey: settings.yaml
    remoteRef:
      key: HOMEPAGE_SETTINGS
  - secretKey: widgets.yaml
    remoteRef:
      key: HOMEPAGE_WIDGETS