tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
      wal:
        path: /var/tempo/wal

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi

persistence:
  enabled: true
  storageClassName: local-path
  size: 10Gi
