apiVersion: v1
kind: ConfigMap
metadata:
  name: flemmarr
data:
  config.yml: |
    sonarr:
      server:
        address: sonarr1.sonarr1
        port: 80
      config:
        host:
          analyticsEnabled: true
        ui:
          firstDayOfWeek: 1
          calendarWeekColumnHeader: ddd MM/DD
          shortDateFormat: YYYY-MM-DD
          longDateFormat: dddd, MMMM D YYYY
          timeFormat: HH:mm
          showRelativeDates: true
          enableColorImpairedMode: true
          theme: auto
          uiLanguage: 1
          id: 1
      rootFolder:
        - path: /data/media/tv
        - path: /data/media/anime
