apiVersion: v1
kind: ConfigMap
metadata:
  name: flemmarr
data:
  config.yml: |
    sonarr:
      server:
        address: sonarr1.sonarr1
        port: 80
      rootFolder:
        - path: /data/media/tv
        - path: /data/media/anime
