apiVersion: v1
kind: ConfigMap
metadata:
  name: flemmarr
data:
  config.yml: |
    sonarr:
      server:
        address: sonarr1.sonarr1
        port: 80
      config:
        host:
          analyticsEnabled: true
        ui:
          firstDayOfWeek: 1
          calendarWeekColumnHeader: ddd MM/DD
          shortDateFormat: YYYY-MM-DD
          longDateFormat: dddd, MMMM D YYYY
          timeFormat: HH:mm
          showRelativeDates: true
          enableColorImpairedMode: true
          theme: auto
          uiLanguage: 1
          id: 1
        mediamanagement:
          autoUnmonitorPreviouslyDownloadedEpisodes: false
          recycleBin: ''
          recycleBinCleanupDays: 7
          downloadPropersAndRepacks: doNotUpgrade
          createEmptySeriesFolders: false
          deleteEmptyFolders: false
          fileDate: none
          rescanAfterRefresh: always
          setPermissionsLinux: false
          chmodFolder: '755'
          chownGroup: ''
          episodeTitleRequired: always
          skipFreeSpaceCheckWhenImporting: false
          minimumFreeSpaceWhenImporting: 50000
          copyUsingHardlinks: true
          useScriptImport: false
          scriptImportPath: ''
          importExtraFiles: true
          extraFileExtensions: srt,sub
          enableMediaInfo: true
          id: 1
        naming:
          renameEpisodes: true
          replaceIllegalCharacters: true
          colonReplacementFormat: 4 #smart replace
          multiEpisodeStyle: 5 #prefixed-range
          standardEpisodeFormat: "{Series TitleYear} - S{season:00}E{episode:00} - {Episode
            CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo
            AudioCodec}{ Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release
            Group}"
          dailyEpisodeFormat: "{Series TitleYear} - {Air-Date} - {Episode CleanTitle} [{Preferred
            Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{
            Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release
            Group}"
          animeEpisodeFormat: "{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000}
            - {Episode CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}[{MediaInfo
            VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo
            AudioLanguages}{-Release Group}"
          seriesFolderFormat: "{Series TitleYear} [imdb-{ImdbId}] - LT"
          seasonFolderFormat: Season {season:00}
          specialsFolderFormat: Specials
          includeSeriesTitle: false
          includeEpisodeTitle: false
          includeQuality: false
          replaceSpaces: true
          separator: " - "
          numberStyle: S{season:00}E{episode:00}
          id: 1
      rootFolder:
        - path: /data/media/tv
        - path: /data/media/anime
