apiVersion: v1
kind: ConfigMap
metadata:
  name: flemmarr
data:
  config.yml: |
    sonarr:
      server:
        address: sonarr1.sonarr1
        port: 80
      config:
        host:
          analyticsEnabled: true
        ui:
          firstDayOfWeek: 1
          calendarWeekColumnHeader: ddd MM/DD
          shortDateFormat: YYYY-MM-DD
          longDateFormat: dddd, MMMM D YYYY
          timeFormat: HH:mm
          showRelativeDates: true
          enableColorImpairedMode: true
          theme: auto
          uiLanguage: 1
          id: 1
        mediamanagement:
          autoUnmonitorPreviouslyDownloadedEpisodes: false
          recycleBin: ''
          recycleBinCleanupDays: 7
          downloadPropersAndRepacks: doNotUpgrade
          createEmptySeriesFolders: false
          deleteEmptyFolders: false
          fileDate: none
          rescanAfterRefresh: always
          setPermissionsLinux: false
          chmodFolder: '755'
          chownGroup: ''
          episodeTitleRequired: always
          skipFreeSpaceCheckWhenImporting: false
          minimumFreeSpaceWhenImporting: 50000
          copyUsingHardlinks: true
          useScriptImport: false
          scriptImportPath: ''
          importExtraFiles: true
          extraFileExtensions: srt,sub
          enableMediaInfo: true
          id: 1
        naming:
          renameEpisodes: true
          replaceIllegalCharacters: true
          colonReplacementFormat: 4 #smart replace
          multiEpisodeStyle: 5 #prefixed-range
          standardEpisodeFormat: "{Series TitleYear} - S{season:00}E{episode:00} - {Episode
            CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo
            AudioCodec}{ Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release
            Group}"
          dailyEpisodeFormat: "{Series TitleYear} - {Air-Date} - {Episode CleanTitle} [{Preferred
            Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{
            Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release
            Group}"
          animeEpisodeFormat: "{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000}
            - {Episode CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}[{MediaInfo
            VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo
            AudioLanguages}{-Release Group}"
          seriesFolderFormat: "{Series TitleYear} [imdb-{ImdbId}] - LT"
          seasonFolderFormat: Season {season:00}
          specialsFolderFormat: Specials
          includeSeriesTitle: false
          includeEpisodeTitle: false
          includeQuality: false
          replaceSpaces: true
          separator: " - "
          numberStyle: S{season:00}E{episode:00}
          id: 1
      rootFolder:
      - path: /data/media/tv
      - path: /data/media/anime
      customformat:
      - includeCustomFormatWhenRenaming: false
        name: LT
        specifications:
        - id: 1
          name: LT
          implementation: ReleaseTitleSpecification
          implementationName: Release Title
          infoLink: https://wiki.servarr.com/sonarr/settings#custom-formats-2
          negate: false
          required: false
          fields:
          - order: 0
            name: value
            label: Regular Expression
            helpText: Custom Format RegEx is Case Insensitive
            value: "\\bLT\\b"
            type: textbox
            advanced: false
            privacy: normal
        - id: 2
          name: LTU
          implementation: ReleaseTitleSpecification
          implementationName: Release Title
          infoLink: https://wiki.servarr.com/sonarr/settings#custom-formats-2
          negate: false
          required: false
          fields:
          - order: 0
            name: value
            label: Regular Expression
            helpText: Custom Format RegEx is Case Insensitive
            value: "\\bLTU\\b"
            type: textbox
            advanced: false
            privacy: normal
      qualityprofile:
      - name: LT
        upgradeAllowed: true
        cutoff: 21
        items:
        - quality:
            id: 0
            name: Unknown
            source: unknown
            resolution: 0
          items: []
          allowed: false
        - quality:
            id: 1
            name: SDTV
            source: television
            resolution: 480
          items: []
          allowed: true
        - name: WEB 480p
          items:
          - quality:
              id: 12
              name: WEBRip-480p
              source: webRip
              resolution: 480
            items: []
            allowed: true
          - quality:
              id: 8
              name: WEBDL-480p
              source: web
              resolution: 480
            items: []
            allowed: true
          allowed: true
          id: 1000
        - quality:
            id: 2
            name: DVD
            source: dvd
            resolution: 480
          items: []
          allowed: true
        - quality:
            id: 13
            name: Bluray-480p
            source: bluray
            resolution: 480
          items: []
          allowed: true
        - quality:
            id: 4
            name: HDTV-720p
            source: television
            resolution: 720
          items: []
          allowed: true
        - quality:
            id: 9
            name: HDTV-1080p
            source: television
            resolution: 1080
          items: []
          allowed: true
        - quality:
            id: 10
            name: Raw-HD
            source: televisionRaw
            resolution: 1080
          items: []
          allowed: true
        - name: WEB 720p
          items:
          - quality:
              id: 14
              name: WEBRip-720p
              source: webRip
              resolution: 720
            items: []
            allowed: true
          - quality:
              id: 5
              name: WEBDL-720p
              source: web
              resolution: 720
            items: []
            allowed: true
          allowed: true
          id: 1001
        - quality:
            id: 6
            name: Bluray-720p
            source: bluray
            resolution: 720
          items: []
          allowed: true
        - name: WEB 1080p
          items:
          - quality:
              id: 15
              name: WEBRip-1080p
              source: webRip
              resolution: 1080
            items: []
            allowed: true
          - quality:
              id: 3
              name: WEBDL-1080p
              source: web
              resolution: 1080
            items: []
            allowed: true
          allowed: true
          id: 1002
        - quality:
            id: 7
            name: Bluray-1080p
            source: bluray
            resolution: 1080
          items: []
          allowed: true
        - quality:
            id: 20
            name: Bluray-1080p Remux
            source: blurayRaw
            resolution: 1080
          items: []
          allowed: true
        - quality:
            id: 16
            name: HDTV-2160p
            source: television
            resolution: 2160
          items: []
          allowed: true
        - name: WEB 2160p
          items:
          - quality:
              id: 17
              name: WEBRip-2160p
              source: webRip
              resolution: 2160
            items: []
            allowed: true
          - quality:
              id: 18
              name: WEBDL-2160p
              source: web
              resolution: 2160
            items: []
            allowed: true
          allowed: true
          id: 1003
        - quality:
            id: 19
            name: Bluray-2160p
            source: bluray
            resolution: 2160
          items: []
          allowed: true
        - quality:
            id: 21
            name: Bluray-2160p Remux
            source: blurayRaw
            resolution: 2160
          items: []
          allowed: true
        minFormatScore: 1
        cutoffFormatScore: 1
        formatItems:
        - format: 1
          name: LT
          score: 1
      downloadclient:
      - name: qbittorrent
        enable: true
        protocol: torrent
        priority: 1
        removeCompletedDownloads: false
        removeFailedDownloads: true
        fields:
        - name: host
          value: qbittorrent.qbittorrent
        - name: port
          value: '80'
        - name: useSsl
          value: false
        - name: urlBase
        - name: username
        - name: password
        - name: tvCategory
          value: sonarr-LT
        - name: tvImportedCategory
        - name: recentTvPriority
          value: 0
        - name: olderTvPriority
          value: 0
        - name: initialState
          value: 0
        - name: sequentialOrder
          value: false
        - name: firstAndLast
          value: false
        implementationName: qBittorrent
        implementation: QBittorrent
        configContract: QBittorrentSettings
        infoLink: https://wiki.servarr.com/sonarr/supported#qbittorrent
        tags: []
