apiVersion: v1
kind: ConfigMap
metadata:
  name: flemmarr
data:
  conif.yml: |
    lidarr:
      server:
        address: localhost
        port: 8686
      config:
        ui:
          uiLanguage: 2 # 1 = English, 2 = French, 3 = Spanish...
      rootfolder:
        - name: Music
          path: /data/music
          defaultTags: []
          defaultQualityProfileId: 1
          defaultMetadataProfileId: 1
