apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flemmarr
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: flemmarr
  dataFrom:
  - extract:
      key: flemmarr
