apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-flannel
resources:
#- ./namespace.yaml
- https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
patches:
- path: patch.configmap.yaml
  target:
    version: v1
    kind: ConfigMap
    name: kube-flannel-cfg
