apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/flannel-io/flannel/releases/download/v0.26.4/kube-flannel.yml
patches:
- path: patch.configmap.yaml
  target:
    version: v1
    kind: ConfigMap
    name: kube-flannel-cfg
