apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: itzg/minecraft-bedrock-server:2023.7.1
        ports:
        - containerPort: 19132
          protocol: UDP
        envFrom:
        - configMapRef:
            name: minecraft
        volumeMounts:
        - name: minecraft-config
          mountPath: /data
      volumes:
      - name: minecraft-config
        persistentVolumeClaim:
          claimName: minecraft-config
