apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: plex
  data:
  - secretKey: PLEX_CLAIM
    remoteRef:
      key: PLEX_CLAIM
