apiVersion: v1
kind: Service
metadata:
  name: plex
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.211
spec:
  ports:
  - name: app
    port: 32400
    targetPort: 32400
    protocol: TCP
    appProtocol: http
  - port: 32410
    targetPort: 32410
    protocol: UDP
    name: gpd-1
  - port: 32412
    targetPort: 32412
    protocol: UDP
    name: gpd-2
  - port: 32413
    targetPort: 32413
    protocol: UDP
    name: gdp-3
  - port: 32414
    targetPort: 32414
    protocol: UDP
    name: gdp-4
  selector:
    app: plex
  type: LoadBalancer
