apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminer
  name: adminer
  namespace: adminer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    appProtocol: http
  selector:
    app: adminer
