apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmGlobals:
  chartHome: charts
helmCharts:
- name: akeyless-api-gateway
  version: latest
  repo: https://akeylesslabs.github.io/helm-charts
  releaseName: akeyless-api-gateway
  namespace: akeyless
  valuesFile: values.yaml
  includeCRDs: true
