apiVersion: v1
kind: ConfigMap
metadata:
  name: hairsera
  namespace: hairsera
data:
  AUTH_URL: https://hair.sync.lt
  AUTH_TRUST_HOST: "true"
  MICROSOFT_TENANT_ID: common
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.otel-collector:4317
  OTEL_SERVICE_NAME: hairsera
  OTEL_SERVICE_VERSION: 0.1.0-develop.86
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev
  LOGO_URL: https://hairsera.lt/wp-content/uploads/2023/08/Hairsera-logo.png
