apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hairsera
  namespace: hairsera
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: hairsera
  dataFrom:
  - extract:
      key: HAIRSERA
