apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hairsera-google-oauth
  namespace: hairsera
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: hairsera-google-oauth
  dataFrom:
  - extract:
      key: GOOGLE_OAUTH_JSON
    rewrite:
    - regexp:
        source: GOOGLE_OAUTH_CLIENT_ID
        target: GOOGLE_CLIENT_ID
    - regexp:
        source: GOOGLE_OAUTH_CLIENT_SECRET
        target: GOOGLE_CLIENT_SECRET
