apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ./components/reloader

resources:
- ./configmap.yaml
- ./externalsecret.yaml
- ./ghcr-pull.externalsecret.yaml
- ./google-oauth.externalsecret.yaml
- ./microsoft-oauth.externalsecret.yaml
- ./migrate.job.yaml
- ./deployment.yaml
- ./service.yaml
- ./ingress.yaml
images:
- name: ghcr.io/aurimasnav/hairsera
  newTag: 0.1.0-develop.46
- name: ghcr.io/aurimasnav/hairsera-migrate
  newTag: 0.1.0-develop.46
