apiVersion: batch/v1
kind: Job
metadata:
  name: hairsera-migrate
  namespace: hairsera
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrate
        image: ghcr.io/aurimasnav/hairsera-migrate:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: hairsera
              key: DATABASE_URL
