apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: plex
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
  - secretKey: admin.password
    remoteRef:
      key: ARGOCD_ADMIN_PASSWORD
