apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.0/manifests/install.yaml
- ./externalsecret.yaml

patches:
- path: patch.service.yaml
  target:
    version: v1
    kind: Service
    name: argocd-server
- path: patch.configmap.yaml
  target:
    version: v1
    kind: ConfigMap
    name: argocd-cm
