apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr-no4k
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: radarr-no4k
  project: default
  source:
    path: gitops/radarr-no4k
    repoURL: https://github.com/AurimasNav/k8s-at-home.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
