apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: ghcr.io/onedr0p/qbittorrent:4.5.2
        ports:
        - containerPort: 8080
          name: webui
          protocol: TCP
        - containerPort: 6881
          name: traffic
          protocol: TCP
        - containerPort: 6881
          name: traffic-udp
          protocol: UDP
        envFrom:
        - configMapRef:
            name: qbittorrent
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: torrents
          mountPath: /torrents
      volumes:
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: qb-config
      - name: torrents
        hostPath:
          path: /data/torrents
          type: Directory
