apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-webui
spec:
  ports:
  - name: app
    port: 80
    targetPort: 8080
    protocol: TCP
    appProtocol: http
  selector:
    app: qbittorrent
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-traffic
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.212
spec:
  ports:
  - name: traffic
    port: 6881
    targetPort: 6881
    protocol: TCP
    appProtocol: TCP
  - name: traffic-udp
    port: 6881
    targetPort: 6881
    protocol: UDP
    appProtocol: UDP
  selector:
    app: qbittorrent
  type: LoadBalancer
