apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  refreshInterval: "1800s"
  secretStoreRef:
    name: doppler-secret-store
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy
    namespace: oauth2-proxy
  data:
  - secretKey: GOOGLE_OAUTH_CLIENT_SECRET
    remoteRef:
      key: OAUTH2_PROXY_COOKIE_SECRET
  - secretKey: OAUTH2_PROXY_CLIENT_ID
    remoteRef:
      key: GOOGLE_OAUTH_CLIENT_ID
  - secretKey: OAUTH2_PROXY_CLIENT_ID
    remoteRef:
      key: GOOGLE_OAUTH_CLIENT_SECRET
  - secretKey: AUTHENTICATED_EMAILS
      key: AUTHENTICATED_EMAILS
